outlier_exclude_cols:
  - ID_Reserva
  - h_res_fec
outlier_pct: 0.01

date_filter:
  START_DATE: "2019-02-13"
  END_DATE: "2020-03-08"


modeling:
  features:
    - day_of_week
    - month
    - lag_1
    - lag_7
    - lag_30
    - rolling_mean_7
    - rolling_mean_21
    - rolling_std_30
    - rolling_trend_7
    - sin_day
    - cos_day
    - is_weekend
    - is_holiday
    - day_of_year
  window_size: 60
  horizon: 1
  n_splits: 6

  transformer:
    input_dim: 14   # == len(features) — update if adding more
    d_model: 128
    nhead: 8
    num_layers: 4
    lr: 0.001
    epochs: 100
    batch_size: 64

  gru:
    input_dim: 14
    hidden_dim: 128
    num_layers: 4
    lr: 0.001
    epochs: 100
    batch_size: 64

  prophet:
    periods: 45

inference:
  year_filter: 2020  # you can remove this if you're using start_date / end_date




optuna_search_space:

  transformer:
    d_model: [64, 128, 256]
    nhead: [4, 8, 16]
    num_layers: [2, 3, 4, 5, 6]
    lr: [0.0001, 0.001, 0.005, 0.01]
    batch_size: [32, 64, 128]
    window_size: [30, 60, 90]
    horizon: [1, 3, 7]

  gru:
    hidden_dim: [64, 128, 256]
    num_layers: [2, 3, 4, 5, 6]
    lr: [0.0001, 0.001, 0.005, 0.01]
    batch_size: [32, 64, 128]
    window_size: [30, 60, 90]
    horizon: [1, 3, 7]

optuna_config:
  n_trials: 20
  seed: 42


