outlier_exclude_cols:
  - ID_Reserva
  - h_res_fec
outlier_pct: 0.01

modeling:
  features:
    - day_of_week
    - month
    - lag_7
    - lag_30
    - rolling_mean_7
    - rolling_mean_21
    - rolling_std_30
    - sin_day
    - cos_day
    - is_weekend
    - day_of_year
  window_size: 90
  horizon: 1
  n_splits: 5

  transformer:
    input_dim: 11        # == len(features)
    d_model: 128
    nhead: 8
    num_layers: 6
    lr: 0.0001
    epochs: 1
    batch_size: 64

  gru:
    input_dim: 11
    hidden_dim: 64
    num_layers: 2
    lr: 0.001
    epochs: 3
    batch_size: 64

  prophet:
    periods: 45

inference:
  year_filter: 2020
