apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-provider
  namespace: development
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: 4347167e-9766-4036-b96a-f40c1dd6dffe
    keyvaultName: keyvaulttcareto
    objects: |
      array:
        - |
          objectName: db-user
          objectType: secret
        - |
          objectName: db-password
          objectType: secret
        - |
          objectName: db-host
          objectType: secret
        - |
          objectName: db-name
          objectType: secret
        - |
          objectName: db-port
          objectType: secret
        - |
          objectName: secret-key
          objectType: secret
        - |
          objectName: algorithm
          objectType: secret
        - |
          objectName: access-token-expire-minutes
          objectType: secret
        - |
          objectName: project-name
          objectType: secret
        - |
          objectName: version
          objectType: secret
        - |
          objectName: api-prefix
          objectType: secret
        - |
          objectName: model-path
          objectType: secret
    tenantId: e263325c-d88f-48ba-9656-b318da27689a
