apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-provider
  namespace: development
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"      # identidad administrada del nodo AKS
    userAssignedIdentityID: ""        # SAI 
    keyvaultName: keyvaulttcareto     # Key Vault
    cloudName: "AzurePublicCloud"     
    tenantId: e263325c-d88f-48ba-9656-b318da27689a
    objects: |
      array:
        - |
          objectName: db-user
          objectType: secret
          objectVersion: ""
        - |
          objectName: db-password
          objectType: secret
          objectVersion: ""
        - |
          objectName: db-host
          objectType: secret
          objectVersion: ""
        - |
          objectName: db-name
          objectType: secret
          objectVersion: ""
        - |
          objectName: db-port
          objectType: secret
          objectVersion: ""
        - |
          objectName: secret-key
          objectType: secret
          objectVersion: ""
        - |
          objectName: algorithm
          objectType: secret
          objectVersion: ""
        - |
          objectName: access-token-expire-minutes
          objectType: secret
          objectVersion: ""
        - |
          objectName: api-base-url
          objectType: secret
          objectVersion: ""
        - |
          objectName: database-url
          objectType: secret
          objectVersion: ""
        - |
          objectName: use-direct-db
          objectType: secret
          objectVersion: ""

  secretObjects:
    - data:
        - key: db-user
          objectName: db-user
      secretName: db-user
      type: Opaque

    - data:
        - key: db-password
          objectName: db-password
      secretName: db-password
      type: Opaque

    - data:
        - key: db-host
          objectName: db-host
      secretName: db-host
      type: Opaque

    - data:
        - key: db-name
          objectName: db-name
      secretName: db-name
      type: Opaque

    - data:
        - key: db-port
          objectName: db-port
      secretName: db-port
      type: Opaque

    - data:
        - key: secret-key
          objectName: secret-key
      secretName: secret-key
      type: Opaque

    - data:
        - key: algorithm
          objectName: algorithm
      secretName: algorithm
      type: Opaque

    - data:
        - key: access-token-expire-minutes
          objectName: access-token-expire-minutes
      secretName: access-token-expire-minutes
      type: Opaque

    - data:
        - key: api-base-url
          objectName: api-base-url
      secretName: api-base-url
      type: Opaque

    - data:
        - key: database-url
          objectName: database-url
      secretName: database-url
      type: Opaque

    - data:
        - key: use-direct-db
          objectName: use-direct-db
      secretName: use-direct-db
      type: Opaque
